# 知识星球快捷登录方式
paicoding:
  login:
    zsxq:
      api: https://wx.zsxq.com/connector/crm/identify_member.html
      appId: 666
      groupNumber: 666
      secret: 666
      redirectUrl: https://paicoding.com/login/zsxq/callback
