log:
  path: ~/logs
env:
  name: pre

spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: true

short-link:
  whitelist: http://localhost:8080,https://paicoding.com/ # 允许创建短链接的域名